### PR TITLE
Provide x264 pkgconfig as cargo metadata

### PR DESCRIPTION
**Pull request by haileys**
Cargo has a feature available to crates that link native libraries allowing them to pass information up to depending libraries.  More detailed documentation is available here: https://doc.rust-lang.org/cargo/reference/build-script-examples.html#using-another-sys-crate

This pull request uses this feature to provide x264's pkgconfig manifest to dependents, allowing their native libraries to link to libx264 directly.

I've had to change the build process to `./configure` libx264 before compilation, and also install it into a prefix under `OUT_DIR`. Running `make install` is necessary to get the pkgconfig templated out with the proper absolute path to the headers and library.

I've also made another unrelated change in this PR - parallelising the build according to the number of CPUs available on the system. If you'd prefer not to take that change in this PR I'm happy to split it out into a separate PR or just remove it.

### CODE REVIEW

**Comment by colbyn** [comment]
Sure, and thanks for the contribution. :)

**Comment by colbyn** [comment]
Okay theres some build problems with this PR. 

For example:
```shell
$ cargo build

...

error: failed to run custom build command for ...

Caused by:
  process didn't exit successfully: `...` (exit code: 101)
--- stdout
platform:      X86_64
byte order:    little-endian
system:        MACOSX
cli:           no
libx264:       internal
shared:        no
static:        yes
asm:           yes
interlaced:    yes
avs:           no
lavf:          no
ffms:          no
mp4:           no
gpl:           yes
thread:        posix
opencl:        yes
filters:       crop select_every
lto:           no
debug:         no
gprof:         no
strip:         no
PIC:           no
bit depth:     all
chroma format: all

You can run 'make' or 'make fprofiled' now.

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:124:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Whats interesting is the `You can run 'make' or 'make fprofiled' now.` line, as though the configure  script was successful.

Presumably the issue is here:
```rust
let result = Command::new("./configure")
        .arg(prefix_arg)
        .arg("--disable-cli")
        .arg("--enable-static")
        .current_dir(&source_path)
        .status()
        .unwrap();
```

To nitpick, it seems like you are implicitly running the process VIA the status function, rather than explicitly, which may lead to better error messages. E.g.
```rust
let result = Command::new("./configure")
        .arg(prefix_arg)
        .arg("--disable-cli")
        .arg("--enable-static")
        .current_dir(&source_path)
        .output()
        .expect("failed to run the x264 ./configure script");
```

Which yields:
```shell
$ cargo build 
...
error: failed to run custom build command for `x264-dev v0.1.1 (...)`

Caused by:
..
failed to run the x264 ./configure script: Os { code: 2, kind: NotFound, message: "No such file or directory" }
...
```
(IDK I’m not too familiar with the `std::process` API. )

Anyway please fix the build issue before merging.

**Comment by haileys** [comment]
@colbyn Hm, that failure is extremely strange. I can't reproduce on either my Mac or a Debian VM. What OS are you using?

**Comment by colbyn** [comment]
@charliesome Oh whoops I should have been more specific. I'm currently running MacOS Catalina (`10.15.3`). 

Although as I mentioned, it's weird that the subprocess prints `You can run 'make' or 'make fprofiled' now.` before panicking. I wonder if this is specific to the subprocess API somehow. My current toolchain setup is: 
```
active toolchain
----------------
stable-x86_64-apple-darwin (default)
rustc 1.43.0 (4fb7144ed 2020-04-20)
```
Also I tested this with latest nightly and got the same result.

**Comment by haileys** [comment]
@colbyn Thanks, that's helpful to know it's a Catalina specific issue - I am running Mojave.

I got a Catalina VM going and was able to reproduce and fix the issue by invoking the configure script as `bash configure` rather than `./configure`. Not sure why `./configure` doesn't work... maybe something to do with the change to zsh? Either way, it should work now if you'd like to try again!

**Comment by colbyn** [comment]
Well looks like everything is working, including the docs.rs build. Thanks for your contribution! 

Also your changes are published on crates (version `0.2.0`).

**Pull request merged**
